"""
Pydantic data schemas for Drone Security Analyst Agent.
Handles telemetry streams, VLM detections, security alerts, and patrol summaries.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class DroneTelemetry(BaseModel):
    """Real-time flight and navigation telemetry from the docked drone."""
    timestamp: str = Field(..., description="ISO timestamp of the reading, e.g. '2026-09-30 00:01:00'")
    latitude: float = Field(..., description="GPS Latitude coordinate")
    longitude: float = Field(..., description="GPS Longitude coordinate")
    altitude_m: float = Field(..., description="Drone altitude above ground level in meters")
    battery_pct: float = Field(..., description="Battery state of charge percentage")
    speed_mps: float = Field(default=0.0, description="Horizontal flight speed in m/s")
    heading_deg: float = Field(default=0.0, description="Heading angle in degrees (0-360)")
    zone_id: str = Field(..., description="Identifier for property zone, e.g. 'ZONE_GATE'")
    zone_name: str = Field(..., description="Human readable zone name, e.g. 'Main Gate'")
    mission_id: str = Field(default="PATROL_001", description="Assigned autonomous patrol mission ID")


class DetectedObject(BaseModel):
    """Fine-grained object detected by the Vision-Language Model or detector."""
    object_id: str = Field(..., description="Unique track/detection identifier")
    label: str = Field(..., description="General category, e.g. 'vehicle', 'person'")
    description: str = Field(..., description="Detailed description, e.g. 'Blue Ford F150 pickup truck'")
    attributes: Dict[str, Any] = Field(default_factory=dict, description="Color, model, clothing, etc.")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    bbox: Optional[List[int]] = Field(default=None, description="[ymin, xmin, ymax, xmax] or [x, y, w, h]")


class FrameAnalysis(BaseModel):
    """Comprehensive analysis of a single synchronized video frame and telemetry."""
    frame_id: str = Field(..., description="Unique frame identifier, e.g. 'FRAME_0001'")
    mission_id: str = Field(default="PATROL_001")
    timestamp: str = Field(..., description="Timestamp of frame capture")
    image_path: str = Field(..., description="File path to the saved visual frame")
    telemetry: DroneTelemetry
    caption: str = Field(..., description="Natural language caption generated by VLM")
    detected_objects: List[DetectedObject] = Field(default_factory=list)
    activity_summary: str = Field(..., description="Contextual activity inference")
    is_alert: bool = Field(default=False)


class SecurityAlert(BaseModel):
    """High-priority security notification triggered by the rules engine."""
    alert_id: str = Field(..., description="Unique alert identifier")
    mission_id: str = Field(default="PATROL_001")
    frame_id: str = Field(..., description="Frame where condition was triggered")
    timestamp: str = Field(..., description="Timestamp of the incident")
    severity: AlertSeverity = Field(default=AlertSeverity.WARNING)
    rule_name: str = Field(..., description="Triggered security policy rule")
    zone_name: str = Field(..., description="Property zone where event occurred")
    description: str = Field(..., description="Concise alert description, e.g. 'Person loitering at main gate, 00:01'")
    context_reason: str = Field(..., description="Why this was triggered based on memory and rule logic")
    suggested_action: str = Field(default="Dispatch security personnel to verify identity")


class PatrolSummary(BaseModel):
    """Mission-level post-flight summary and analytics report."""
    mission_id: str
    start_time: str
    end_time: str
    total_frames: int
    total_alerts: int
    alerts_by_severity: Dict[str, int]
    one_sentence_summary: str
    executive_summary: str
    key_events: List[str]
    zones_covered: List[str]
